### ISSUE TITLE
Fix color reference in emphasis-block

### ISSUE THREAD

**Issue by scanieso** [freshtilledsoil/base-style-framework#3]
[emphasis-block.scss](https://github.com/freshtilledsoil/base-style-framework/blob/master/stylesheets/modules/_emphasis-block.scss)

Currently has 5 char hex value. Can probably replace with color variable.

**Comment by scottaohara** [comment]
Fixed w/ latest commit [https://github.com/freshtilledsoil/base-style-framework/commit/6894627a1db5a83c2cae0d77081235de8c630e61]
