### ISSUE TITLE
manifest vs base-styles

### ISSUE THREAD

**Issue by scottaohara** [freshtilledsoil/base-style-framework#4]
What's the purpose of having both a manifest.scss and the base-styles.scss?

I thought we said we were likely to change the file name anyway, so I didn't see the reason to change it.

**Comment by timwright12** [comment]
Needs to be cleaned up

**Comment by scottaohara** [comment]
pushed a commit to differentiate base styles (only base styles to match the UI Kit) and manifest (all the things)
